# Site settings
utensils:
  # an avatar or logo (optional)
  logo: "/assets/img/utensils-icon.png"
  title: "utensils.io"
  # Obfuscated email
  # instructions: bundle exec rake email
  email-key: RwUizVYPO9fqXThnr5tNABpSE6KQD3MIymGeCL271dgJ04H8vxckojWsFlabuZ
  email-encoded: P9GLnPL@5LWGXphX.p9
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: false

# Build settings
markdown: kramdown

plugins:
  - github-pages
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - README.md
   - Rakefile
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
