title: utensils.io
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

thanks: "/thanks/" # after form submitted, send visitor here
email-key: NKkExcBXbwYMgnjeV5AHtZhilCDW8RySzG0dJIULvsqf27puQrm41oTaFP9O63
email-encoded: lYzLglL@xL0z6qf6.qY
logo: utensils-plain.png # used in schema.org

# Build settings
plugins:
  - kramdown
  - uglifier
  - jekyll-assets
  - jekyll-archives
  - jekyll-compose
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

source: src
destination: www
markdown: kramdown
    
compress_html:
  ignore:
    envs: ["development"]
  clippings: []
  comments: all
  endings: []
  startings: []
  blanklines: false
  profile: false

assets:
  sources:
  - _assets/vendor
  - _assets/favicon
  digest: true
  compression: true
  gzip: false
  defaults:
    js: { integrity: false } # true on JEKYLL_ENV=production
    css: { integrity: false } # true on JEKYLL_ENV=production
    img: { integrity: false } # true on JEKYLL_ENV=production
  compress:
    css: false
    js: uglifier

paginate: 4
paginate_path: /blog/:num/
permalink: /blog/:categories/:title/

jekyll-archives:
  enabled: ['categories', 'tags', 'year']
  layout: default
  layouts:
    year: archive-date
    category: archive-catalog
    tag: archive-catalog
  permalinks:
    year: '/blog/:year/'
    tag: '/blog/tag/:name/'
    category: '/blog/:name/'

defaults: # hide blog pages from sitemap until complete
  -
    scope:
      path: "blog" 
    values:
      sitemap: false
include:
  - CNAME
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
