name: Build

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
